### ISSUE TITLE
How do tags work?

### ISSUE THREAD

**Issue by JonathanReeve** [ChrisPenner/Slick#1]
I notice that some of the posts in the example site have tags, but I don't see the tags implemented anywhere in the site output. How would one go about making a page that listed all tags, and their associated posts?

**Comment by ChrisPenner** [comment]
Yes @JonathanReeve, @steshaw  is correct; there's nothing provided inside Slick for managing tags, it's quite tricky to do generically due to the way Shake caches things. Feel free to copy my approach though; as @steshaw said you can find it in `getTags` and `buildTag` here: https://github.com/ChrisPenner/ChrisPenner.github.io/blob/slick/app/Main.hs

You may also want to take a look at my other project [SitePipe](https://github.com/ChrisPenner/sitepipe); it does have rudimentary tag builder support built in, but unfortunately does not support caching between builds. You can see an example of SitePipe with tags here: https://github.com/ChrisPenner/SitePipe/blob/master/examples/blog/app/Main.hs
