### ISSUE TITLE
Stack

### ISSUE THREAD

**Issue by locallycompact** [ChrisPenner/slick#14]
Is it alright if I add this to stack?

**Comment by ChrisPenner** [comment]
Absolutely 😄 ; I just didn't get around to it initially, but if you don't mind figuring out some good package bounds and adding it in I'm game 👍

**Comment by tintinthong** [comment]
@locallycompact yes pls. Is this still being undertaken @locallycompact and @ChrisPenner?? I also have some issues getting Slick to work with haskell-language-server. I believe its because the lts version is not supported by hls. Hence, it would be nice to get a version with a higher-lts that is compatible with haskell-language-server

**Comment by ChrisPenner** [comment]
I upgraded the stack.yaml and ensured it builds against `lts-16.29`; but unfortunately can't add it to stackage ATM due to [this issue](https://github.com/commercialhaskell/stackage/issues/5567) with pandoc 😢 

I'm not entirely sure how the lts version of the underlying package would affect HLS, if the package builds with the GHC you're using with HLS it should handle it fine AFAIK.

Regardless, feel free to try the [updated version of slick](https://hackage.haskell.org/package/slick-1.1.0.0) and see if that helps 😄

**Comment by ChrisPenner** [comment]
Pandoc issue has been resolved 🎉 

Slick will be available in the next available stackage LTS 😄 
https://github.com/commercialhaskell/stackage/pull/5967
